# Generated by Django 4.2.5 on 2023-09-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало рассылки')),
                ('end_date', models.DateTimeField(verbose_name='Окончание рассылки')),
                ('periodicity', models.DurationField(verbose_name='Периодичность')),
                ('status', models.CharField(default='Создана', verbose_name='Статус')),
                ('clients', models.ManyToManyField(to='mailings.clients', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.messages', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailingsettings', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'логи рассылки',
                'verbose_name_plural': 'логи рассылок',
            },
        ),
    ]
