# Generated by Django 4.2.5 on 2023-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_messages_mailingsettings_mailinglogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
